


import { type Metadata } from "next";
import { Toaster } from "~/components/ui/toaster";


export const metadata: Metadata = {
  title: "Uni Shop",
  description: "Generated by PULSE",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    
      <>
      
          {children}
          <Toaster />
          </>
  );
}
