export interface SpecialItems {
  item_special_tags_assign_id?: number,
  category_type_id?: number,
  item_id?: number,
  item_special_tags_id?: number,
  tag_name?: string | null,
  outlet_id?: number,
  item_name?: string | null,
  expiry_date?: string | null,
  barcode?: string | null,
  URL?: null,
  introduced?: string | null,
  category?: number,
  detail?: string | null,
  deleted?: number,
  item_sale_price?: number,
  discount_amount?: number | null,
  discount_percentage?: number | null,
  items_type?: number | null,
  parent_item?: string | null,
  SKU?: string | null,
  SKU_title?: string | null,
  tax_id?: number | null,
  event_price?: number | null,
  event_check?: number | null,
  cost_price?: string | null,
  weighable?: number | null,
  tax_exempted?: number | null,
  stockable_item?: number | null,
  readyMade?: number | null,
  available?: string | null,
  returnable?: number | null,
  product_id?: number | null,
  category_name?: string | null,
  food_id?: number | null,
  food_name?: string | null,
  book_id?: number | null,
  book_title?: string | null,
  object_path?: string | null,
}

export interface SpecialItemsApiResponse {
  status: boolean,
  data?: SpecialItems[] | null
} 