import "~/styles/globals.css";
// import { Suspense } from "react";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { AuthProvider } from "~/Context/AuthContext";
import { Toaster } from "~/components/ui/toaster";
import { Suspense } from "react";
// import Loading from "./loading";

export const metadata: Metadata = {
  title: "Uni Shop",
  description: "Generated by PULSE",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body suppressHydrationWarning>

        <AuthProvider>
          {children}
          <Toaster />
        </AuthProvider>

      </body>
    </html>
  );
}
