import "~/styles/globals.css";
// import { Suspense } from "react";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { BackgroundBeamsWithCollision } from "~/components/ui/background-beams-with-collision";
import Footer from "~/components/footer";
import { AuthProvider } from "~/Context/AuthContext";
// import Loading from "./loading";

export const metadata: Metadata = {
  title: "Uni Shop",
  description: "Generated by PULSE",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body suppressHydrationWarning>
        {/* <Suspense fallback={<Loading />}> */}
          <AuthProvider>
            <BackgroundBeamsWithCollision>
              {children}
            </BackgroundBeamsWithCollision>
          </AuthProvider>
          <Footer />
        {/* </Suspense> */}
      </body>
    </html>
  );
}
