import { type Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "UniShop | Merch Books and Beyond",
  description: "Generated by PULSE",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return <>
    <Suspense fallback={<></>}>
      {children}
    </Suspense>
  </>;
}
